CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE sessions (
   id SERIAL PRIMARY KEY,
   token TEXT NOT NULL UNIQUE,
   "userId" INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE links (
	id SERIAL NOT NULL PRIMARY KEY,
	"shortenUrl" TEXT NOT NULL,
	"url" TEXT NOT NULL,
	"userId" INTEGER NOT NULL REFERENCES users(id),
	"viewsCount" INTEGER NOT NULL DEFAULT 0
);